# Generated by Django 5.2.4 on 2025-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('institution_name', models.CharField(default='КМДА', max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Діючий'), ('former', 'Колишній'), ('temporary', 'Тимчасовий')], default='active', max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials/photos/')),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='officials_o_name_f37374_idx'), models.Index(fields=['institution_name'], name='officials_o_institu_a97bb5_idx')],
            },
        ),
    ]
