# Generated by Django 5.2.4 on 2025-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deputy_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
